---
- hosts: webservers
  tasks:
    - name: Download NodeJS 14.X Source
      shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
      
    - name: Install NodeJS 
      become: yes
      apt:
        name: nodejs
        state: present
      tags:
         - package
    
    - name: Clone the Webapp repo from github
      ansible.builtin.git:
        repo: https://github.com/GShwartz/bootcamp-app.git
        dest: ~/bootcamp-app/
        clone: yes
        update: yes
    
    - name: Copy ENV file to bootcamp-app
      ansible.builtin.copy:
        src: ~/env-stage
        dest: ~/bootcamp-app/.env
        follow: no
  
    - name: Creates an entry in crontab
      ansible.builtin.cron:
        name: "run webapp"
        special_time: reboot
        job: "cd ~/bootcamp-app/ && npm run dev"
        
    - name: Install "Weight-Tracker" node.js package.
      script: ~/postfresh.sh
     
    - name: Reboot remote servers
      become: yes
      ansible.builtin.reboot:
        msg: "Reboot by Ansible"
        pre_reboot_delay: 1
