---
- hosts: webservers
  tasks:
    # Download NodeJS 14.x repo
    - name: Download NodeJS 14.X Source
      shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
    
    # Install NodeJS 14    
    - name: Install NodeJS 
      become: yes
      apt:
        name: nodejs
        state: present
      
      # In case the user want to skip this stage or play just this one for debugging.
      tags:
         - package
    
    # Get the webapp repo from GitHub
    - name: Clone the Webapp repo from github
      ansible.builtin.git:
        repo: https://github.com/GShwartz/bootcamp-app.git
        dest: ~/bootcamp-app/
        clone: yes
        update: yes
    
    # Copy pre-made env file to target's dir
    - name: Copy ENV file to bootcamp-app
      ansible.builtin.copy:
        src: ~/env-stage
        dest: ~/bootcamp-app/.env
        follow: no
  
    # Add a Crontab entry to restart the app if the machine reboots.
    - name: Creates an entry in crontab
      ansible.builtin.cron:
        name: "run webapp"
        special_time: reboot
        job: "cd ~/bootcamp-app/ && npm run dev"
    
    # Install Webapp package with NodeJS
    - name: Install WebApp JS Package
      ansible.builtin.shell: 
        chdir: ~/bootcamp-app/
        cmd: npm install
        
    # Sync & Init app with DB
    - name: Initalize App's Database
      ansible.builtin.shell: 
        chdir: ~/bootcamp-app/
        cmd: npm run initdb
        
    #- name: Install "Weight-Tracker" node.js package.
    #  script: ~/postfresh.sh
    
    # Reboot remote host as finale
    - name: Reboot remote servers
      become: yes
      ansible.builtin.reboot:
        msg: "Reboot by Ansible"
        pre_reboot_delay: 2
